
module.exports = {
	INIT_CHAT_CONTAINER : "INIT_CHAT_CONTAINER",
	INIT_CHAT_CONTAINER_SUCCESS : "INIT_CHAT_CONTAINER_SUCCESS",
	INIT_CONNECTION_MADE : "INIT_CONNECTION_MADE",
	CHAT_SESSION_STARTED : "CHAT_SESSION_STARTED",
	GET_USERS_DATA_FOR_CHANNEL : "GET_USERS_DATA_FOR_CHANNEL_SUCCESS",
	GET_USERS_DATA_FOR_CHANNEL_SUCCESS : "GET_USERS_DATA_FOR_CHANNEL_SUCCESS",
	UPDATE_SCREEN_FOR_CHANNEL_SUCCESS : "UPDATE_SCREEN_FOR_CHANNEL_SUCCESS",
	UPDATE_SCREEN_FOR_CHANNEL : "UPDATE_SCREEN_FOR_CHANNEL",
	SCREEN_UPDATE_EVENT : "SCREEN_UPDATE_EVENT",
	UPDATE_DISCUSSIONS_LIST : "UPDATE_DISCUSSIONS_LIST",
	UPDATE_RIGHT_PANEL_FOR_CHANNEL : "UPDATE_RIGHT_PANEL_FOR_CHANNEL",
	CHANGE_CHANNEL : "CHANGE_CHANNEL",
	AUTH_NEEDED : "AUTH_NEEDED"
}