module.exports = {
  INIT_CONTAINER: 'INIT_CONTAINER',
  AUTH_NEEDED: 'AUTH_NEEDED',
  MY_CLICK_DONE_SUCCESS: 'MY_CLICK_DONE_SUCCESS',
  APP_STATE_CHANGED: 'APP_STATE_CHANGED',
  APP_STATE_INIT: 'APP_STATE_INIT',
  FETCH_APPS_SUCCESS: 'FETCH_APPS_SUCCESS',
  APPS_FETCH_STATE_SUCCESS: 'APPS_FETCH_STATE_SUCCESS'
}
